---
- name: Manage RouterOS
  hosts: 192.168.124.1
  vars:
    ansible_remote_tmp: "/tmp/ansible-$USER"
  gather_facts: no
  collections:
    - community.routeros
  tasks:
    - name: Execute a command on RouterOS
      community.routeros.command:
        commands:
          - /system identity print
