---
- name: Test RouterOS
  hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: community.routeros.routeros
    ansible_command_timeout: 1600
  gather_facts: no
  collections:
    - community.routeros
  tasks:
    - name: Execute a command on RouterOS
      community.routeros.command:
        commands:
          - /system identity set name=TEST
