---
- name: Test Win
  hosts: 10.0.105.12
  gather_facts: no
  collections:
    - ansible.windows.win_package
 ansible.windows.win_package:
    path: C:\temp\7z.exe
    creates_path: C:\Program Files\7-Zip\7z.exe
    creates_version: 16.04
    state: present
